[[redirects]]
from="/health/*"
to="/"
status=200

[[redirects]]
from="/tech/*"
to="/"
status=200

[[redirects]]
from="/docs/*"
to="/"
status=200

[[redirects]]
from="/exporer/*"
to="/"
status=200
