[[redirects]]
from="/docs"
to="/"
status=200

[[redirects]]
from="/docs/get-started/*"
to="/"
status=200

[[redirects]]
from="/docs/conventions/*"
to="/"
status=200

[[redirects]]
from="/docs/faq/*"
to="/"
status=200

[[redirects]]
from="/health"
to="/"
status=200

[[redirects]]
from="/health/issues/*"
to="/"
status=200

[[redirects]]
from="/tech/*"
to="/"
status=200
